apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: yelb-ui-hpa
  namespace: yelb
spec:
  maxReplicas: 6
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: yelb-ui
  targetCPUUtilizationPercentage: 20
